### ISSUE TITLE
[JOSS review] Various formats for input structure

### ISSUE THREAD

**Issue by AndySAnker** [FrederikLizakJohansen/DebyeCalculator#21]
This is part of the review feedback for JOSS submission (https://github.com/openjournals/joss-reviews/issues/6024)

@marcocamma suggests to add functionality of providing the input as tuple (atoms_list,xyz_array).

related to the point above, would it make sense to move generate_nanoparticles as standalone utility function.
it could take a cif and a radius and return atom_list,xyz_position ?

**Comment by FrederikLizakJohansen** [comment]
Thank you for the suggestion. We think this is very relevant to how the package will be used in the future, which is why I am currently doing some major restructuring of the way that we handle input and output of the five functions: `iq`, `sq`, `fq`, `gr` and `_get_all` (on branch [issue-21](https://github.com/FrederikLizakJohansen/DebyeCalculator/tree/issue-21)), including the possibility of providing input as tuples (atoms_list,xyz_array). The restructuring naturally incorporates the suggestion (#20) of using namedtuples to better organize the various outputs of each function. Most recent commit can be found here 620c6b8 

An update regarding `generate_nanoparticles` will follow

**Comment by FrederikLizakJohansen** [comment]
Updates for the current issue (check out the [issue-21 branch](https://github.com/FrederikLizakJohansen/DebyeCalculator/tree/issue-21)):

- Improved `iq`, `sq`, `fq`, `gr`, and `_get_all `functions. They can now handle input in the form of tuples with atoms listed as either numbers or element names.

- Changed the output of `iq`, `sq`, `fq`, `gr`, and `_get_all `to use namedtuples with more meaningful names. This tweak was based on feedback from issue #20.

- Moved the `generate_nanoparticles `function to the utility folder as a standalone function and updated it.

I'll be adding more unit tests before merging everything with the main branch.

**Comment by FrederikLizakJohansen** [comment]
The changes have now been merged to the main branch and the functions are working as [intented](https://github.com/FrederikLizakJohansen/DebyeCalculator/actions/runs/7245417561).

I am closing the issue here. Thank you again for the suggestion.
