### ISSUE TITLE
[JOSS review] Names could be less ambiguous

### ISSUE THREAD

**Issue by elena-pascal** [FrederikLizakJohansen/DebyeCalculator#27]
This is part of the review feedback for JOSS submission (https://github.com/openjournals/joss-reviews/issues/6024)

I am going to keep track here of user facing variables that could be more precise.

- [ ] `structure_path` is not just the path but the file name as well
I think naming it `structure_file` would be more clear. If you do want to emphasise that a path can be provided it seem that you have the code for that in `DebyeCalculator().interact()`

All the computation return tuples of parameters in reverse order from the name of the method. Is this on purpose?
- [ ] `calc.iq` returns Q, I
- [ ] `calc.sq` returns Q, S
- [ ] `calc.fq` returns Q, F
- [ ] `calc.gr` returns r, G
Another reviewer mentioned that `namedtuples` would improve this situation and I agree, I think giving outputs more precise names,  together with `namedtuples` for the two parameters would make the output more intuitive; ie. `calc.scattering_intensity()` would return `ScatteringIntensity(values, points)/ (y, x)/(ordinate, abscissa)...`. It also feels like those second return parameters are optional (?)

**Comment by AndySAnker** [comment]
Thank you for the suggestion of changing the naming of the variables. 

We have now renamed `structure_path` to `structure_source`. This change is more in line with the expanded input formats that were developed after the feedback in suggestion #21.

> All the computation return tuples of parameters in reverse order from the name of the method. Is this on purpose?

Yes, that's intentional. The functions return Q and I (in that order) since it's customary to plot Q on the x-axis. However, we usually refer to it as Iq in discussions. Therefore we named the function `calc.iq`. This naming follows the convention used in DiffPy-CMI. To address your `namedtuples` point, we have updated the output so it can be accessed in two ways:

Directly: 
`q, iq = calc.iq(...)`

Via namedtuple: 
`scattering = calc.iq(...)`
`q = scattering.q` 
`iq = scattering.i`

I am closing this issue. Feel free to reopen the issue if you would like to see any further changes made to this.
