### ISSUE TITLE
Not able to calculate for .cif files.

### ISSUE THREAD

**Issue by maak-sdu** [FrederikLizakJohansen/DebyeCalculator#36]
Dear DebyeCalculator dev team,

I wanted to try out your code and followed your installation instructions. It works perfectly fine for me, when using the named tuple in the example of usage, as well as for .xyz files given as example data. However, for .cif files given as example data as well as other .cif files from various sources (database entries of ICSD, COD,  and MP and various outputs from DiffPy, FullProf, and VESTA), I keep encountering errors when trying to calculate *I(Q)*. The most common error seems to be related to centering of the generated supercell. I tried to vary the size value of `radii` given to the calculator but with no change.

Any assistance would be highly appreciated. In case you would appreciate any error message(s), please let me know.

Best,
Martin

**Comment by FrederikLizakJohansen** [comment]
Hi Martin,
First of all, thank you for your interest in the project, we highly appreciate your feedback.

I was immediately able to replicate the error that you are experiencing, and I was surprised to find that one of our dependencies, namely ASE, has changed their "centering"-function in their latest update, something which I cannot seem to find in their release notes. This unfortunately breaks our nanoparticle generation script.

A temporary solution is to downgrade ASE to version 3.22.1. If you are using pip, you can use `pip install ase==3.22.1` within your python environment. On my side, this seems to do the trick.

We are planning on releasing a new version of DebyeCalculator in the coming weeks, and I will make sure that this is fixed for later versions. I will keep this issue open until then.

Let me know if this fix does not work for you, and I will be happy to look further into the problem.

Best,
Frederik

**Comment by maak-sdu** [comment]
Hi @FrederikLizakJohansen,

Thank for the prompt reply - it also does the trick on my side!
I'll keep an eye out for your next release.

Best,
Martin

**Comment by FrederikLizakJohansen** [comment]
@maak-sdu 
Since the issue breaks a major part of the codebase, we ultimately decided to put out an early release (1.0.8) that fixes the problem of the dependency, by restricting the ASE version being installed when you install DebyeCalculator. This is a temporary fallback fix, and will need to be handled at a later stage in order to be up to date with the latest release of ASE. 

The new version is live on pypi and so should be easy to install via pip.

Thank you again for putting this to our attention. I am closing the issue here. Please re-open it if you experience any more problems in the future relating to this issue.
