### ISSUE TITLE
Allow for specifiying the precision when constructing `DebyeCalculator`

### ISSUE THREAD

**Issue by miguelgondu** [FrederikLizakJohansen/DebyeCalculator#38]
In some scenarios (e.g. fitting GPs and doing BO) it's important to keep double precision. But I've been told double precision can be too costly when computing scattering patterns.

Could you allow for specifying the default torch float type in the constructor of `DebyeCalculator`?

**Comment by miguelgondu** [comment]
@AndySAnker

**Comment by FrederikLizakJohansen** [comment]
Thank you for your suggestion! We think it makes a lot of sense to allow for double precision as well. From testing, it seems like we are able to support single- and double precision for now. Half precision seems to introduce some instabilities when calculating small values. 

Double-precision can be specified using the `dtype` parameter when initialising a DebyeCalculator object:
```
calc = DebyeCalculator(dtype=torch.float64)
```

This feature will be a part of the next release of DebyeCalculator.
I am closing the issue here. Feel free to reopen the issue if you would like to see any further changes made to this.
