### ISSUE TITLE
 Issue with iq() function when using cif files

### ISSUE THREAD

**Issue by sara-mokhtari** [FrederikLizakJohansen/DebyeCalculator#41]
Hello,

First of all, thank you very much for this  package.

I wanted to bring to your attention on an issue I encountered while using the iq() function with a CIF file as input. The following error occurs:

...
--> 207 cell.center(about=0.)
File "~/Python3/Debye_calc/lib/python3.11/site-packages/ase/atoms.py", line 1323, in Atoms.center
1321         if n in axes:
1322             translation -= vector / 2.0
-> 1323             translation[n] += about[n]
1325 self.positions += translation
TypeError: 'float' object is not subscriptable

This issue seems to come from a recent change in ASE, where the center() function no longer accepts a float as an argument. Instead, it requires "about " to be explicitly defined as a list or array. For example, modifying the center definition to cell.center(about=[0.0, 0.0, 0.0]) resolves the issue.

I am also contacting the ASE team to address this change, but I wanted to let you know that, as of now, using CIF files with Debye_Calculator is not functional due to this compatibility issue.

Thank you for your time and for the work you've put into this package.

Best regards,

Sara.

**Comment by FrederikLizakJohansen** [comment]
Hi Sara,
Thank you for bringing this to our attention. Could you kindly share the version of ASE you are using? This will help us replicate the problem on our end and work towards resolving it.

-F

**Comment by sara-mokhtari** [comment]
Hello again,

Thank you for your fast response, I'm using the latest version of ASE which is 3.23.0. 

Sara

**Comment by FrederikLizakJohansen** [comment]
Hi Sara,
We strongly recommend installing DebyeCalculator through its PyPI distribution ([DebyeCalculator on PyPI](https://pypi.org/project/debyecalculator/)). This ensures that you are using the supported versions of all dependencies. Currently, DebyeCalculator only supports ASE < 3.23.0. (because of other compatibility reasons).

This version restriction is enforced during installation (as specified in the [pyproject.toml](https://github.com/FrederikLizakJohansen/DebyeCalculator/blob/main/pyproject.toml)). When installing DebyeCalculator, the process will automatically downgrade ASE to a compatible version or abort if a suitable version cannot be installed.

To resolve the issue, we recommend the following steps:

Uninstall your current ASE installation to ensure there are no conflicting versions:

```bash
pip uninstall ase
```
Reinstall DebyeCalculator via PyPI. This will automatically install a compatible version of ASE:

```bash
pip install debyecalculator
```
We are actively working to support newer versions of ASE and other dependencies in future updates.

Please let us know if you encounter any issues during reinstallation or need further assistance. I am closing the issue here, but you are welcome to open another issue requesting support for ASE 3.23.0

**Comment by sara-mokhtari** [comment]
My apologies, I didn't see that an < 3.23.0 ASE version  was necessary, it is indeed solving the issue.

Thank you a lot for your help.

And good luck for the rest of the work ! 

Sara
